apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: knote
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongo-app
  template:
    metadata:
      labels:
        app: mongo-app
    spec:
      containers:
        - name: mongo-container
          image: mongo
          ports:
            - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: knote
spec:
  selector:
    app: mongo-app
  ports:
    - protocol: 'TCP'
      port: 27017
      targetPort: 27017
  type: ClusterIP