# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: argocd-github-secret
#   namespace: argocd
# stringData:
#   token: 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
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-alpha
  namespace: argocd
spec:
  sourceRepos:
  - https://github.com/kirupakaran369/agrocd-demo.git
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  - namespace: jenkins
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-alpha
  namespace: argocd
spec:
  project: project-alpha
  source:
    repoURL: https://github.com/kirupakaran369/agrocd-demo.git
    targetRevision: master
    path: Application/Jenkins
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  # sourceSecret:
  #   name: argocd-github-secret
  #   namespace: argocd
