---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-test
  namespace: argocd
spec:
  sourceRepos:
  - https://github.com/kirupakaran369/agrocd-demo.git
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  - namespace: demo
    server: https://kubernetes.default.svc
  - namespace: default
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-test
  namespace: argocd
spec:
  project: project-test
  source:
    repoURL: https://github.com/kirupakaran369/agrocd-demo.git
    targetRevision: master
    path: Application/Karpenter
  destination: 
  - server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
