---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-wordpress
  namespace: argocd
spec:
  sourceRepos:
  - https://github.com/kirupakaran369/agrocd-demo.git
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  - namespace: wordpress
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-app
  namespace: argocd
spec:
  project: project-wordpress
  source:
    repoURL: https://github.com/kirupakaran369/agrocd-demo.git
    targetRevision: main
    path: Application/wordpress
  destination: 
    namespace: wordpress
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
