apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: jenkins-provisioners
spec:
  labels:
    intent: apps
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot", "on-demand"]
    - key: karpenter.k8s.aws/instance-size
      operator: NotIn
      values: [nano, micro, small, medium, large]
  # limits:
  #   resources:
  #     cpu: 1000
  #     memory: 1000Gi
  ttlSecondsAfterEmpty: 30
  ttlSecondsUntilExpired: 2592000
  providerRef:
    name: default
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: jenkins-awsnodetemplate
spec:
  subnetSelector:
    alpha.eksctl.io/cluster-name: KTraining-cluster
  securityGroupSelector:
    alpha.eksctl.io/cluster-name: KTraining-cluster
  tags:
    KarpenerProvisionerName: "default"
    NodeType: "karpenter-workshop"
    IntentLabel: "apps"