apiVersion: v1
kind: Service
metadata:
  name: wp-svc-2
  namespace: wordpress
spec:
  selector:
    app: wordpress-2
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 80
  type: NodePort
